name: "Publish Snapshot Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Publish-Snapshot:
    uses: eclipse-edc/.github/.github/workflows/publish-snapshot.yml@main
    secrets: inherit

  Publish-Dependencies:
    uses: eclipse-edc/.github/.github/workflows/publish-dependencies.yml@main
    secrets: inherit
